name: 'Personal Jekyll Theme'
description: 'Responsive Image Full Page'
url: 'https://mohamadrido.github.io/personal-jekyll-theme'
author: 'Mohamad Rido'
email: 'mohamad.rido@yandex.com'
permalink: /:title
plugin:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
markdown: kramdown
highlighter: rouge
paginate: 3
